apiVersion: v1
kind: Service
metadata:
 name: tomcat
 labels:
   app: tomcat
spec:
 type: NodePort
 selector:
   matchLabels:
     app: tomcat
 ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      nodePort: 30009
      targetPort: 8080
